---
# Playbook to add/update linux user - entries all in vars section of playbook
- hosts: all
  vars:
    user_name: "user1"
    user_details: "User 1"
    groups: "users"
    uid: "1010"
    password: "abc1234"

  tasks:
    # Add/Update users
    - name: Add/Update user {{ user_name }}
      user:
        name: "{{ user_name }}"
        state: present
        comment: "{{ user_details }}"
        uid: "{{ uid }}"
        groups: "{{ groups }}"
        password: "{{ password | password_hash('sha512') }}"
