---
# Playbook to add/update linux users using variables file
- hosts: all

  tasks:
    - name: Import configure users role
      import_role:
        name: configure_users
      register: configure_users_output
