---
# Playbook to apply sysctl tunings
- hosts: all
  become: yes

  tasks:
    - name: Import SAP HANA role to tune sysctl values 
      import_role:
        name: HANA_sysctl_tunings 
      
    - name: Show HANA sysctl tuning output 
      debug:
        msg: "Output: {{ HANA_sysctl_output }}"
        verbosity: 1

    - name: Show HANA sysctl tuning output vars
      debug:
        var: HANA_sysctl_output 
        verbosity: 1
