---
# Playbook to remove SAP HANA VGs, LVs and FSs
- hosts: all
  become: yes

  tasks:
    - name: Import SAP HANA role to remove VGs, LVs and FSs 
      import_role:
        name: delete_HANA_LVs
      register: delete_HANA_LVs_ouput
      
    - name: Show HANA delete output 
      debug:
        var: delete_HANA_LVs_ouput
        verbosity: 1
