---
# Playbook to remove SAP HANA VGs, LVs and FSs
- hosts: HANA
  become: yes

  tasks:
    - name: Import SAP HANA role to remove VGs, LVs, FS and delete volumes with OpenStack
      import_role:
        name: delete_HANA_LVs_OS
