---
# Playbook to create a HANA VG, LV and filesystem
# Create required VGs, LVs and FSs
- hosts: all
  become: yes
 
  tasks:
    - name: Import SAP HANA role to create VGs, LVs and FSs 
      import_role:
        name: create_HANA_LVs_OS
      register: create_HANA_LVs_ouput
      
    - name: Show HANA create output 
      debug:
        var: create_HANA_LVs_ouput
        verbosity: 1
