---
# tasks file for configure_users
# Add/Update users
- name: Add/Update users
  user:
    name: "{{ item.user_name }}"
    state: "{{ item.state }}"
    comment: "{{ item.user_details }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password | password_hash('sha512') }}"
  loop: "{{ users }}"
  become: yes
